# fase2_aprovisionamiento/inventario.ini
# EP3 - DRY7122 | Alumno: 001V-07

[routers]
csr1kv ansible_host=192.168.56.101 ansible_user=cisco ansible_password=cisco123! ansible_network_os=ios ansible_connection=network_cli
